server:
  port: 8080

spring:
  application:
    name: library-project

  datasource:
    url: jdbc:postgresql://localhost:5432/library-project
    username: postgres
    password: 8986Kh-4
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
